#!/bin/bash
set -e
sudo -l sudo || exit
sudo yum install -y \
  axel \
  emacs \
  tree \
  wget \

mkdir -p ~/.dotfiles.bak
: $(
  cd ~
  tar -c --exclude .dotfiles.bak . | tar -x -C .dotfiles.bak
)
tar -c --exclude .ssh . | tar -x -C ~
source ~/.bashrc
